<a href="https://colab.research.google.com/github/lotnik1005/akademia/blob/master/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

np.float64(19.209372712298546)

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p - q)

np.float64(5.0)

In [ ]:
import numpy as np
X = np.array([[5, 3], [3, 9]])
Y = np.array([1], [2])
print(X, '\n')
print(Y)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [ ]:
Z = np.dot(X, Y)

NameError: name 'Y' is not defined

In [ ]:
import numpy as np
A = np.array({[2, 4], [-1, 3]})
np.linalg.det(A)

TypeError: unhashable type: 'list'

In [ ]:
import numpy as np

A = np.array([[2, 4],
              [-1, 3]])
print(np.linalg.det(A))

9.999999999999998


In [ ]:
np.trace(A)

np.int64(5)

In [1]:
import numpy as np
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [2]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [5]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]
